#if defined(ZLS_FUNC_DEFTYPES)
#undef ZLS_FUNC_DEFTYPES
#define ZLS_FUNC(ret, funcname, parms)  typedef ret (*PType##funcname)parms
#elif defined(ZLS_FUNC_DEFVARS)
#undef ZLS_FUNC_DEFVARS
#define ZLS_FUNC(ret, funcname, parms)  PType##funcname funcname
#elif defined(ZLS_FUNC_SETVARS)
#undef ZLS_FUNC_SETVARS
#define ZLS_FUNC(ret, funcname, parms)  gl::funcname = (PType##funcname)dlsym(hnd_gles, #funcname)
#endif

ZLS_FUNC(void         , glActiveTexture, (GLenum texture));
ZLS_FUNC(void         , glAttachShader, (GLuint program, GLuint shader));
ZLS_FUNC(void         , glBindAttribLocation, (GLuint program, GLuint index, const GLchar* name));
ZLS_FUNC(void         , glBindBuffer, (GLenum target, GLuint buffer));
ZLS_FUNC(void         , glBindFramebuffer, (GLenum target, GLuint framebuffer));
ZLS_FUNC(void         , glBindRenderbuffer, (GLenum target, GLuint renderbuffer));
ZLS_FUNC(void         , glBindTexture, (GLenum target, GLuint texture));
ZLS_FUNC(void         , glBlendColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
ZLS_FUNC(void         , glBlendEquation, ( GLenum mode ));
ZLS_FUNC(void         , glBlendEquationSeparate, (GLenum modeRGB, GLenum modeAlpha));
ZLS_FUNC(void         , glBlendFunc, (GLenum sfactor, GLenum dfactor));
ZLS_FUNC(void         , glBlendFuncSeparate, (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha));
ZLS_FUNC(void         , glBufferData, (GLenum target, GLsizeiptr size, const GLvoid* data, GLenum usage));
ZLS_FUNC(void         , glBufferSubData, (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid* data));
ZLS_FUNC(GLenum       , glCheckFramebufferStatus, (GLenum target));
ZLS_FUNC(void         , glClear, (GLbitfield mask));
ZLS_FUNC(void         , glClearColor, (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha));
ZLS_FUNC(void         , glClearDepthf, (GLclampf depth));
ZLS_FUNC(void         , glClearStencil, (GLint s));
ZLS_FUNC(void         , glColorMask, (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha));
ZLS_FUNC(void         , glCompileShader, (GLuint shader));
ZLS_FUNC(void         , glCompressedTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid* data));
ZLS_FUNC(void         , glCompressedTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid* data));
ZLS_FUNC(void         , glCopyTexImage2D, (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border));
ZLS_FUNC(void         , glCopyTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height));
ZLS_FUNC(GLuint       , glCreateProgram, (void));
ZLS_FUNC(GLuint       , glCreateShader, (GLenum type));
ZLS_FUNC(void         , glCullFace, (GLenum mode));
ZLS_FUNC(void         , glDeleteBuffers, (GLsizei n, const GLuint* buffers));
ZLS_FUNC(void         , glDeleteFramebuffers, (GLsizei n, const GLuint* framebuffers));
ZLS_FUNC(void         , glDeleteProgram, (GLuint program));
ZLS_FUNC(void         , glDeleteRenderbuffers, (GLsizei n, const GLuint* renderbuffers));
ZLS_FUNC(void         , glDeleteShader, (GLuint shader));
ZLS_FUNC(void         , glDeleteTextures, (GLsizei n, const GLuint* textures));
ZLS_FUNC(void         , glDepthFunc, (GLenum func));
ZLS_FUNC(void         , glDepthMask, (GLboolean flag));
ZLS_FUNC(void         , glDepthRangef, (GLclampf zNear, GLclampf zFar));
ZLS_FUNC(void         , glDetachShader, (GLuint program, GLuint shader));
ZLS_FUNC(void         , glDisable, (GLenum cap));
ZLS_FUNC(void         , glDisableVertexAttribArray, (GLuint index));
ZLS_FUNC(void         , glDrawArrays, (GLenum mode, GLint first, GLsizei count));
ZLS_FUNC(void         , glDrawElements, (GLenum mode, GLsizei count, GLenum type, const GLvoid* indices));
ZLS_FUNC(void         , glEnable, (GLenum cap));
ZLS_FUNC(void         , glEnableVertexAttribArray, (GLuint index));
ZLS_FUNC(void         , glFinish, (void));
ZLS_FUNC(void         , glFlush, (void));
ZLS_FUNC(void         , glFramebufferRenderbuffer, (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer));
ZLS_FUNC(void         , glFramebufferTexture2D, (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level));
ZLS_FUNC(void         , glFrontFace, (GLenum mode));
ZLS_FUNC(void         , glGenBuffers, (GLsizei n, GLuint* buffers));
ZLS_FUNC(void         , glGenerateMipmap, (GLenum target));
ZLS_FUNC(void         , glGenFramebuffers, (GLsizei n, GLuint* framebuffers));
ZLS_FUNC(void         , glGenRenderbuffers, (GLsizei n, GLuint* renderbuffers));
ZLS_FUNC(void         , glGenTextures, (GLsizei n, GLuint* textures));
ZLS_FUNC(void         , glGetActiveAttrib, (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name));
ZLS_FUNC(void         , glGetActiveUniform, (GLuint program, GLuint index, GLsizei bufsize, GLsizei* length, GLint* size, GLenum* type, GLchar* name));
ZLS_FUNC(void         , glGetAttachedShaders, (GLuint program, GLsizei maxcount, GLsizei* count, GLuint* shaders));
ZLS_FUNC(int          , glGetAttribLocation, (GLuint program, const GLchar* name));
ZLS_FUNC(void         , glGetBooleanv, (GLenum pname, GLboolean* params));
ZLS_FUNC(void         , glGetBufferParameteriv, (GLenum target, GLenum pname, GLint* params));
ZLS_FUNC(GLenum       , glGetError, (void));
ZLS_FUNC(void         , glGetFloatv, (GLenum pname, GLfloat* params));
ZLS_FUNC(void         , glGetFramebufferAttachmentParameteriv, (GLenum target, GLenum attachment, GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetIntegerv, (GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetProgramiv, (GLuint program, GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetProgramInfoLog, (GLuint program, GLsizei bufsize, GLsizei* length, GLchar* infolog));
ZLS_FUNC(void         , glGetRenderbufferParameteriv, (GLenum target, GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetShaderiv, (GLuint shader, GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetShaderInfoLog, (GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* infolog));
ZLS_FUNC(void         , glGetShaderPrecisionFormat, (GLenum shadertype, GLenum precisiontype, GLint* range, GLint* precision));
ZLS_FUNC(void         , glGetShaderSource, (GLuint shader, GLsizei bufsize, GLsizei* length, GLchar* source));
ZLS_FUNC(const GLubyte* , glGetString, (GLenum name));
ZLS_FUNC(void         , glGetTexParameterfv, (GLenum target, GLenum pname, GLfloat* params));
ZLS_FUNC(void         , glGetTexParameteriv, (GLenum target, GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetUniformfv, (GLuint program, GLint location, GLfloat* params));
ZLS_FUNC(void         , glGetUniformiv, (GLuint program, GLint location, GLint* params));
ZLS_FUNC(int          , glGetUniformLocation, (GLuint program, const GLchar* name));
ZLS_FUNC(void         , glGetVertexAttribfv, (GLuint index, GLenum pname, GLfloat* params));
ZLS_FUNC(void         , glGetVertexAttribiv, (GLuint index, GLenum pname, GLint* params));
ZLS_FUNC(void         , glGetVertexAttribPointerv, (GLuint index, GLenum pname, GLvoid** pointer));
ZLS_FUNC(void         , glHint, (GLenum target, GLenum mode));
ZLS_FUNC(GLboolean    , glIsBuffer, (GLuint buffer));
ZLS_FUNC(GLboolean    , glIsEnabled, (GLenum cap));
ZLS_FUNC(GLboolean    , glIsFramebuffer, (GLuint framebuffer));
ZLS_FUNC(GLboolean    , glIsProgram, (GLuint program));
ZLS_FUNC(GLboolean    , glIsRenderbuffer, (GLuint renderbuffer));
ZLS_FUNC(GLboolean    , glIsShader, (GLuint shader));
ZLS_FUNC(GLboolean    , glIsTexture, (GLuint texture));
ZLS_FUNC(void         , glLineWidth, (GLfloat width));
ZLS_FUNC(void         , glLinkProgram, (GLuint program));
ZLS_FUNC(void         , glPixelStorei, (GLenum pname, GLint param));
ZLS_FUNC(void         , glPolygonOffset, (GLfloat factor, GLfloat units));
ZLS_FUNC(void         , glReadPixels, (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* pixels));
ZLS_FUNC(void         , glReleaseShaderCompiler, (void));
ZLS_FUNC(void         , glRenderbufferStorage, (GLenum target, GLenum internalformat, GLsizei width, GLsizei height));
ZLS_FUNC(void         , glSampleCoverage, (GLclampf value, GLboolean invert));
ZLS_FUNC(void         , glScissor, (GLint x, GLint y, GLsizei width, GLsizei height));
ZLS_FUNC(void         , glShaderBinary, (GLsizei n, const GLuint* shaders, GLenum binaryformat, const GLvoid* binary, GLsizei length));
ZLS_FUNC(void         , glShaderSource, (GLuint shader, GLsizei count, const GLchar** string, const GLint* length));
ZLS_FUNC(void         , glStencilFunc, (GLenum func, GLint ref, GLuint mask));
ZLS_FUNC(void         , glStencilFuncSeparate, (GLenum face, GLenum func, GLint ref, GLuint mask));
ZLS_FUNC(void         , glStencilMask, (GLuint mask));
ZLS_FUNC(void         , glStencilMaskSeparate, (GLenum face, GLuint mask));
ZLS_FUNC(void         , glStencilOp, (GLenum fail, GLenum zfail, GLenum zpass));
ZLS_FUNC(void         , glStencilOpSeparate, (GLenum face, GLenum fail, GLenum zfail, GLenum zpass));
ZLS_FUNC(void         , glTexImage2D, (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* pixels));
ZLS_FUNC(void         , glTexParameterf, (GLenum target, GLenum pname, GLfloat param));
ZLS_FUNC(void         , glTexParameterfv, (GLenum target, GLenum pname, const GLfloat* params));
ZLS_FUNC(void         , glTexParameteri, (GLenum target, GLenum pname, GLint param));
ZLS_FUNC(void         , glTexParameteriv, (GLenum target, GLenum pname, const GLint* params));
ZLS_FUNC(void         , glTexSubImage2D, (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels));
ZLS_FUNC(void         , glUniform1f, (GLint location, GLfloat x));
ZLS_FUNC(void         , glUniform1fv, (GLint location, GLsizei count, const GLfloat* v));
ZLS_FUNC(void         , glUniform1i, (GLint location, GLint x));
ZLS_FUNC(void         , glUniform1iv, (GLint location, GLsizei count, const GLint* v));
ZLS_FUNC(void         , glUniform2f, (GLint location, GLfloat x, GLfloat y));
ZLS_FUNC(void         , glUniform2fv, (GLint location, GLsizei count, const GLfloat* v));
ZLS_FUNC(void         , glUniform2i, (GLint location, GLint x, GLint y));
ZLS_FUNC(void         , glUniform2iv, (GLint location, GLsizei count, const GLint* v));
ZLS_FUNC(void         , glUniform3f, (GLint location, GLfloat x, GLfloat y, GLfloat z));
ZLS_FUNC(void         , glUniform3fv, (GLint location, GLsizei count, const GLfloat* v));
ZLS_FUNC(void         , glUniform3i, (GLint location, GLint x, GLint y, GLint z));
ZLS_FUNC(void         , glUniform3iv, (GLint location, GLsizei count, const GLint* v));
ZLS_FUNC(void         , glUniform4f, (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
ZLS_FUNC(void         , glUniform4fv, (GLint location, GLsizei count, const GLfloat* v));
ZLS_FUNC(void         , glUniform4i, (GLint location, GLint x, GLint y, GLint z, GLint w));
ZLS_FUNC(void         , glUniform4iv, (GLint location, GLsizei count, const GLint* v));
ZLS_FUNC(void         , glUniformMatrix2fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value));
ZLS_FUNC(void         , glUniformMatrix3fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value));
ZLS_FUNC(void         , glUniformMatrix4fv, (GLint location, GLsizei count, GLboolean transpose, const GLfloat* value));
ZLS_FUNC(void         , glUseProgram, (GLuint program));
ZLS_FUNC(void         , glValidateProgram, (GLuint program));
ZLS_FUNC(void         , glVertexAttrib1f, (GLuint indx, GLfloat x));
ZLS_FUNC(void         , glVertexAttrib1fv, (GLuint indx, const GLfloat* values));
ZLS_FUNC(void         , glVertexAttrib2f, (GLuint indx, GLfloat x, GLfloat y));
ZLS_FUNC(void         , glVertexAttrib2fv, (GLuint indx, const GLfloat* values));
ZLS_FUNC(void         , glVertexAttrib3f, (GLuint indx, GLfloat x, GLfloat y, GLfloat z));
ZLS_FUNC(void         , glVertexAttrib3fv, (GLuint indx, const GLfloat* values));
ZLS_FUNC(void         , glVertexAttrib4f, (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w));
ZLS_FUNC(void         , glVertexAttrib4fv, (GLuint indx, const GLfloat* values));
ZLS_FUNC(void         , glVertexAttribPointer, (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid* ptr));
ZLS_FUNC(void         , glViewport, (GLint x, GLint y, GLsizei width, GLsizei height));

#undef ZLS_FUNC